### ISSUE TITLE
Plz Update Source v.1.4.5

### ISSUE THREAD

**Issue by aroxu** [RajneeshSingh007/MusicX-Music-Player#3]
@RajneeshSingh007 
Please update source for researching.
Please update source v.1.4.5

**Comment by xxczaki** [comment]
@smileappslab 

![musicx music player - android apps on google play](https://user-images.githubusercontent.com/22645979/29333809-8282469e-8205-11e7-9afd-23fa1c3428b5.png)

**Comment by RajneeshSingh007** [comment]
@xxczaki Yeah, he published whole app with same icon, except changes in package name,author name, not included any licenses but now it is removed by google.
Due to this issue, i'm not uploading latest source.😅

_Sent from my Meizu m3 note using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
